version: 2

sources:
  - name: stackoverflow
    database: bigquery-public-data
    schema: stackoverflow
    tables:
      - name: questions
        identifier: posts_questions
      - name: answers
        identifier: posts_answers
      - name: votes
        identifier: votes